"""Add OAuth fields

Revision ID: 764939155698
Revises: a0740aa3509f
Create Date: 2026-02-27 12:46:54.953023

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '764939155698'
down_revision = 'a0740aa3509f'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('email', sa.String(length=255), nullable=True))
    op.add_column('users', sa.Column('auth_provider', sa.String(length=50), nullable=True))
    op.add_column('users', sa.Column('provider_id', sa.String(length=255), nullable=True))
    op.alter_column('users', 'phone',
               existing_type=sa.VARCHAR(length=20),
               nullable=True)
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_unique_constraint(None, 'users', ['provider_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='unique')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.alter_column('users', 'phone',
               existing_type=sa.VARCHAR(length=20),
               nullable=False)
    op.drop_column('users', 'provider_id')
    op.drop_column('users', 'auth_provider')
    op.drop_column('users', 'email')
    # ### end Alembic commands ###
